apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: mozjyto4r-python-gitops
  description: This is GitOps manifest for mozjyto4r-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=mozjyto4r-python
    backstage.io/kubernetes-id: mozjyto4r-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: mozjyto4r-python   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:mozjyto4r-python
